{
    'name': "Shawon Module",
    'version': "19.0.1.0",
    'summary': "Learning Odoo development",
    'description': "This module is created for learning purpose",
    'author': "Saiful Islam Shawon",
    'category': "Custom",
    'depends': ['base'],
    'data': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
    'sequence': 1,
}
